CXX = clang++
CXXFLAGS = -std=c++11

all: ElevatorSim

ElevatorSim: Elevator.o
    $(CXX) $(CXXFLAGS) -o ElevatorSim Elevator.o

Elevator.o: Elevator.cpp Elevator.h
    $(CXX) $(CXXFLAGS) -c Elevator.cpp

clean:
    rm -f *.o ElevatorSim
